CREATE DATABASE SENAI_WISHLIST_TARDE

USE SENAI_WISHLIST_TARDE

CREATE TABLE USUARIOS(
	ID INT IDENTITY PRIMARY KEY,
	EMAIL VARCHAR(255) NOT NULL UNIQUE,
	SENHA VARCHAR(255) NOT NULL
);

CREATE TABLE DESEJOS(
	ID INT IDENTITY PRIMARY KEY,
	DESCRICAO VARCHAR(255) NOT NULL,
	DATACRIACAO	DATE NOT NULL,
	IDUSUARIO INT NOT NULL FOREIGN KEY REFERENCES USUARIOS(ID)
);

select * from USUARIOS

INSERT INTO USUARIOS VALUES('a@a.a', '123456' )